return {
    lspkind_symbols = {
      Text = " 󰉿 ",
      Method = " 󰆧 ",
      Function = " 󰊕 ",
      Constructor = "  ",
      Field = " 󰜢 ",
      Variable = " 󰀫 ",
      Class = " 󰠱 ",
      Interface = "  ",
      Module = "  ",
      Property = " 󰜢 ",
      Unit = " 󰑭 ",
      Value = " 󰎠 ",
      Enum = "  ",
      Keyword = " 󰌋 ",
      Snippet = "  ",
      Color = " 󰏘 ",
      File = " 󰈙 ",
      Reference = " 󰈇 ",
      Folder = " 󰉋 ",
      EnumMember = "  ",
      Constant = " 󰏿 ",
      Struct = " 󰙅 ",
      Event = "  ",
      Operator = " 󰆕 ",
      TypeParameter = " ",
      Calc = " 󰃬 ",
      minuet = "󱗻",
      HF = "",
      OpenAI = "",
      Ollama = "",
      Codestral = "",
      Bard = "",
    },
}
